version: "3"

tasks:
  generate_sso:
    aliases:
      - gen_sso
    desc: "Generate code from sso proto file"
    cmds:
      - protoc -I proto proto/sso/sso.proto --go_out=./gen/go --go_opt=paths=source_relative --go-grpc_out=./gen/go/ --go-grpc_opt=paths=source_relative
  generate_logs:
    aliases:
      - gen_sso
    desc: "Generate code from log proto files"
    cmds:
      - protoc -I proto proto/logs/logs.proto --go_out=./gen/go --go_opt=paths=source_relative --go-grpc_out=./gen/go/ --go-grpc_opt=paths=source_relative
